create table ARTICLE (
  id bigint generated by default as identity primary key,
  name varchar(255),
  title varchar(1000),
  body clob
);

create table ARTICLE_COMMENT (
  id bigint generated by default as identity primary key,
  article_id bigint not null,
  name varchar(255),
  body varchar(2000)
);

create table product (
  id bigint generated by default as identity primary key,
  name varchar(255),
  total_amount bigint,
  started_at datetime(6),
  finished_at datetime(6)
);

create table investment (
  id varchar(40) primary key,
  product_id bigint,
  amount bigint,
  created_at datetime(6)
);

create table investment_event (
  id varchar(40) primary key,
  product_id bigint,
  amount bigint,
  created_at datetime(6)
);